spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database?escapeSyntaxCallMode=callIfNoReturn
    username: kyc_user
    password: kyc_pass
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

  graphql:
    schema:
      printer:
        enabled: true

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: /opt/kyc/kyc-config-files/keystore.p12
    key-store-password: test
    key-alias: backbone-key