spring:
  application:
    name: kyc-customers-data
  profiles:
    active: dev
  jackson:
    default-property-inclusion: NON_NULL

  graphql:
    path: /customer-data

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false


logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

kyc-messages:
  catalog:
    messages:
      "000":
        code: KYC-CUSTOMERS-DATA-000
        message: Unexpected Error
        type: ERROR
      "001":
        code: KYC-CUSTOMERS-DATA-001
        message: The request is invalid
        type: ERROR
      "002":
        code: KYC-CUSTOMERS-DATA-002
        message: The operation cannot be performed at this moment
      "003":
        code: KYC-CUSTOMERS-DATA-003
        message: The customer already exists
